/**
 * branches.js — x0s KCET Branch List
 * Used for autocomplete in Disha KCET predictor
 * Add more branches below as needed
 */
 
window.XOS_BRANCHES = [
  'AEROSPACE ENGINEERING',
  'AGRICULTURAL ENGINEERING',
  'ARTIFICIAL INTELLIGENCE',
  'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE',
  'ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING',
  'AUTOMOBILE ENGINEERING',
  'BIOMEDICAL ENGINEERING',
  'BIOTECHNOLOGY',
  'CHEMICAL ENGINEERING',
  'CIVIL ENGINEERING',
  'COMPUTER SCIENCE AND BUSINESS SYSTEMS',
  'COMPUTER SCIENCE AND DESIGN',
  'COMPUTER SCIENCE AND ENGINEERING',
  'COMPUTER SCIENCE AND ENGINEERING (AI)',
  'COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)',
  'COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)',
  'COMPUTER SCIENCE AND ENGINEERING (IOT)',
  'ELECTRICAL AND ELECTRONICS ENGINEERING',
  'ELECTRICAL ENGINEERING',
  'ELECTRONICS AND COMMUNICATION ENGINEERING',
  'ELECTRONICS AND INSTRUMENTATION ENGINEERING',
  'ENVIRONMENTAL ENGINEERING',
  'FOOD TECHNOLOGY',
  'INDUSTRIAL ENGINEERING AND MANAGEMENT',
  'INFORMATION SCIENCE AND ENGINEERING',
  'INSTRUMENTATION TECHNOLOGY',
  'MARINE ENGINEERING',
  'MECHANICAL ENGINEERING',
  'MECHATRONICS',
  'MEDICAL ELECTRONICS',
  'MINING ENGINEERING',
  'POLYMER SCIENCE AND TECHNOLOGY',
  'ROBOTICS AND ARTIFICIAL INTELLIGENCE',
  'TEXTILE TECHNOLOGY',
 
  // ── ADD MORE BRANCHES BELOW ──
];
 
